# docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: auth-system-db
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: authsystem
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: